# Generated by Django 2.2.13 on 2020-07-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
